---

- name: Test distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Create playbook-unique fact
  set_fact:
    yumrepo_unique: "{{ ansible_date_time.iso8601_micro }}"
  when: yumrepo_unique is not defined

- name: Configure additional repos in /etc/yum.repos.d/
  template:
    src: yum_repo.j2
    dest: /etc/yum.repos.d/{{ item.key }}.repo
  with_dict: yumrepo_repos
  when: yumrepo_repos.keys() | length > 0
  notify:
    - Delete unmanaged repos

- name: Create temporal directory
  file:
    path: /tmp/ansible.yumrepo.{{ yumrepo_unique }}
    state: directory
  changed_when: False

- name: Create fragments for repos to be ignored
  lineinfile:
    line: "{{ item }}"
    dest: /tmp/ansible.yumrepo.{{ yumrepo_unique }}/{{ item }}
    create: yes
    state: present
  with_items: yumrepo_ignore_repos
  changed_when: False
  when: yumrepo_ignore_repos | length > 0

- name: Create fragment files
  lineinfile:
    line: "{{ item.key }}.repo"
    dest: /tmp/ansible.yumrepo.{{ yumrepo_unique }}/{{ item.key }}
    create: yes
    state: present
  with_dict: yumrepo_repos
  changed_when: False
  when: yumrepo_repos.keys() | length > 0

- name: Touch the .processed file
  shell: touch /tmp/ansible.yumrepo.{{ yumrepo_unique }}/.processed
  changed_when: False
  when: not yumrepo_finish

- name: Check if the the .processed file exists
  stat:
    path: /tmp/ansible.yumrepo.{{ yumrepo_unique }}/.processed
  register: processed

- name: Create managed file
  assemble:
    src: /tmp/ansible.yumrepo.{{ yumrepo_unique }}
    dest: /etc/yum.repos.d/.managed
    regexp: '^[^\.].*'
  when: processed.stat.exists and yumrepo_finish
  notify:
    - Delete unmanaged repos

- name: Delete the fragment directory
  shell: rm -fr "/tmp/ansible.yumrepo.{{ yumrepo_unique }}x"
  changed_when: False
  when: yumrepo_finish
